
<!DOCTYPE html>
<html lang="">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link href="CSS/style.css" rel="stylesheet">


    <title><?php echo $view->pageTitle; ?></title>
</head>

<?php
if ($_SESSION['isLoggedIn']){
    echo '
<body lang="en">
    <nav>
        
            <div class="col-lg-11 col-md-12">
                <div class="">
                    <img src="Images/logo.png" width="25%" height="40%" class="d-inline-block align-text-top " alt="">
                </div>
                <!--style="float: right"  action="../../index.php"-->
                <div class="d-inline">
                    <form class="d-inline p-2" method="post">
                        <input type="text" name="searchInput" placeholder="Search for Entry" value="';
                        if (isset($_SESSION['sInput'])){echo $_SESSION['sInput'];}?><?php echo'" required>
                        <button class="btn btn-primary" type="submit" name="searchButton">Search</button>
                    </form>
                </div>
                
                <div class="d-inline" >
                    <form class="d-inline p-2" method="post">
                        <button class="btn btn-secondary" type="submit" name="resetSearch">Show All</button>
                    </form>
                </div>
                <div style="float: right" class="d-inline nav justify-content-end">
                    <form class="d-inline p-2 nav-item"  method="post">
                        <label  class="">Welcome, ';  echo $_SESSION['username'] . '</label>
                        <button  class="btn btn-danger" name="logout" type="submit" id="logout"><a>Log out</a></button>
                        
                    </form>
                </div>
                
            </div>
        
    </nav>
</body>
    ';
}
?>





